apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Bloodhound Postgres
    type: postgres
    url: postgres:5432
    database: bloodhound
    user: bloodhound
    secureJsonData:
      password: bloodhound
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: false
